import requests

r = requests.put('http://httpbin.org/put',data={'key':'value'})
print(dir(r))
print('\napparent_encoding:')
print(r.apparent_encoding)
print('\nencoding:')
print(r.encoding)
print('\nheaders:')
print(r.headers)
print('\nhistory:')
print(r.history)
print('\njson:')
print(r.json())
print('\nrequest:')
print(r.request)
print('\nstatus_code:')
print(r.status_code)
print('\ntext:')
print(r.text)
print('\nurl:')
print(r.url)